// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyDialog: typeof import('./src/components/dialog/MyDialog.vue')['default']
    MyLoading: typeof import('./src/components/loading/MyLoading.vue')['default']
    PlayVideo: typeof import('./src/components/play/PlayVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanLoading: typeof import('vant/es')['Loading']
  }
}
