# Generated by Django 5.2.7 on 2025-10-24 14:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('tag_type', models.CharField(choices=[('skill', '技能标签'), ('interest', '兴趣标签'), ('system', '系统标签'), ('custom', '自定义标签')], default='custom', max_length=20, verbose_name='标签类型')),
                ('tag_name', models.CharField(help_text='请输入标签名称，最多100个字符', max_length=100, unique=True, verbose_name='标签名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(blank=True, help_text='可选，最多500个字符', max_length=500, null=True, verbose_name='标签描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'user_tags',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['tag_type', 'is_active'], name='user_tags_tag_typ_c8d12e_idx'), models.Index(fields=['tag_name'], name='user_tags_tag_nam_00be26_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTagRelationship',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='关联ID')),
                ('relation_time', models.DateTimeField(auto_now_add=True, verbose_name='关联时间')),
                ('weight', models.FloatField(default=1.0, help_text='0-1之间的数值，表示关联强度', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='关联权重')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('pending', '待审核'), ('rejected', '已拒绝')], default='active', max_length=20, verbose_name='关联状态')),
                ('relation_description', models.TextField(blank=True, help_text='可选，描述用户与此标签的具体关系', max_length=300, null=True, verbose_name='关联描述')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='tag.tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户-标签关联',
                'verbose_name_plural': '用户-标签关联',
                'db_table': 'user_tag_relationships',
                'ordering': ['-relation_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_tag_re_user_id_3f5e51_idx'), models.Index(fields=['tag', 'status'], name='user_tag_re_tag_id_59fd80_idx'), models.Index(fields=['relation_time'], name='user_tag_re_relatio_a3f098_idx')],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
