# Generated by Django 5.2.7 on 2025-10-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertagrelationship',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
