# Generated by Django 5.2.7 on 2025-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(default=10000, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='用户年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], default=0, verbose_name='用户性别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='电话号码')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'user',
                'ordering': ['-create_time'],
            },
        ),
    ]
