# Generated by Django 5.2.7 on 2025-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_icon',
            field=models.TextField(blank=True, null=True, verbose_name='用户头像'),
        ),
    ]
